[phases.setup]
nixPkgs = ["python39", "pip"]
cmds = ["echo 'Using requirements/production.txt for installation'"]

[phases.install]
cmds = ["pip install -r requirements/production.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn config.wsgi --log-file -"