services:
  - type: web
    name: cms-progress-sql
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: cms-progress-sql.onrender.com
      - key: STATIC_URL
        value: /static/
      - key: MEDIA_URL
        value: /media/
    healthCheckPath: /
    autoDeploy: true

  - type: pserv
    name: cms-progress-sql-db
    env: postgresql
    plan: starter
    ipAllowList: []
    maxConnections: 10
    maintenanceWindow: sun-00:00
    terminationProtection: false
