# Generated by Django 4.0.8 on 2025-08-28 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_percent', models.FloatField(default=0.0)),
                ('course_grades_avg', models.FloatField(default=0.0)),
                ('grade_avg', models.FloatField(default=0.0)),
                ('credit_hours', models.FloatField(default=0.0)),
                ('age_at_enroll', models.FloatField(default=0.0)),
                ('days_since_last_login', models.FloatField(default=0.0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('residency', models.CharField(blank=True, max_length=32, null=True)),
                ('financial_aid', models.CharField(blank=True, max_length=32, null=True)),
                ('pandemic_effect', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=32)),
                ('predicted_marks', models.FloatField()),
                ('features_snapshot', models.JSONField()),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pred_requested', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
