# Generated by Django 4.0.8 on 2025-09-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_lecturer_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='subject',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='lecturer',
            index=models.Index(fields=['name'], name='core_lectur_name_247f32_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturer',
            index=models.Index(fields=['subject'], name='core_lectur_subject_b25e90_idx'),
        ),
    ]
