# Generated by Django 4.0.8 on 2025-08-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_lab_user_is_lab_assistant_user_is_librarian_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labassistant',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='labassistant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='librarian',
            name='user',
        ),
        migrations.RemoveField(
            model_name='officeassistant',
            name='department',
        ),
        migrations.RemoveField(
            model_name='officeassistant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_lab_assistant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_librarian',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_office_assistant',
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
        migrations.DeleteModel(
            name='LabAssistant',
        ),
        migrations.DeleteModel(
            name='Librarian',
        ),
        migrations.DeleteModel(
            name='OfficeAssistant',
        ),
    ]
