# Generated by Django 4.0.8 on 2025-08-31 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_collegecalendar_attendancesession_attendance'),
        ('accounts', '0004_remove_labassistant_lab_remove_labassistant_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.batch'),
        ),
    ]
