# Generated by Django 4.0.8 on 2025-09-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_number',
            field=models.CharField(blank=True, help_text='Unique enrollment number for result checking', max_length=20, null=True, unique=True),
        ),
    ]
