# Generated by Django 4.0.8 on 2025-09-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_student_enrollment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='feedback_submitted',
            field=models.BooleanField(default=False, help_text='Whether the student has submitted mandatory feedback'),
        ),
    ]
